# Generated by Django 4.1.2 on 2022-12-11 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_product_image_orderproduct_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='image',
        ),
    ]
