# Generated by Django 4.1.2 on 2022-12-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_orderproduct_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='color',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
